Don't use now-removed Exception.message attribute
BaseException.message has been deprecated since Python 2.6 [0] and
does not exist in Python 3 (CPython's ebe3e16600).  As a result, the
user sees messages like

    $ git-when-merged not-valid
    [...]
    Traceback (most recent call last):
      File "bin/git-when-merged", line 550, in main
        commit = rev_parse('%s^{commit}' % (options.commit,))
      File "bin/git-when-merged", line 207, in rev_parse
        raise Failure('%r is not a valid commit!' % (arg,))
    __main__.Failure: 'not-valid^{commit}' is not a valid commit!

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "bin/git-when-merged", line 647, in <module>
        main(sys.argv[1:])
      File "bin/git-when-merged", line 552, in main
        sys.exit(e.message)
    AttributeError: 'Failure' object has no attribute 'message'

When the exception is used as a string formatting argument, simply
drop ".message".  Otherwise, obtain the message with str().

[0]: https://www.python.org/dev/peps/pep-0352/